# Generated by Django 5.2.3 on 2025-06-30 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_score', models.FloatField(default=0.0)),
                ('title_confidence', models.FloatField(default=0.0)),
                ('type_confidence', models.FloatField(default=0.0)),
                ('context_confidence', models.FloatField(default=0.0)),
                ('language_confidence', models.FloatField(default=0.0)),
                ('date_confidence', models.FloatField(default=0.0)),
                ('source_confidence', models.FloatField(default=0.0)),
                ('version_confidence', models.FloatField(default=0.0)),
                ('url_confidence', models.FloatField(default=0.0)),
                ('raw_extraction_data', models.JSONField(default=dict)),
                ('processing_time', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extraction_result', to='documents.document')),
            ],
            options={
                'verbose_name': "Résultat d'extraction",
                'verbose_name_plural': "Résultats d'extraction",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtractionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échoué')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extraction_tasks', to='documents.document')),
            ],
            options={
                'verbose_name': "Tâche d'extraction",
                'verbose_name_plural': "Tâches d'extraction",
                'ordering': ['-started_at'],
            },
        ),
    ]
