# Generated by Django 5.2.3 on 2025-06-30 04:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('extraction', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extractiontask',
            options={'ordering': ['-created_at'], 'verbose_name': "Tâche d'extraction", 'verbose_name_plural': "Tâches d'extraction"},
        ),
        migrations.RemoveField(
            model_name='extractionresult',
            name='context_confidence',
        ),
        migrations.RemoveField(
            model_name='extractionresult',
            name='date_confidence',
        ),
        migrations.RemoveField(
            model_name='extractionresult',
            name='language_confidence',
        ),
        migrations.RemoveField(
            model_name='extractionresult',
            name='raw_extraction_data',
        ),
        migrations.RemoveField(
            model_name='extractionresult',
            name='source_confidence',
        ),
        migrations.RemoveField(
            model_name='extractionresult',
            name='title_confidence',
        ),
        migrations.RemoveField(
            model_name='extractionresult',
            name='type_confidence',
        ),
        migrations.RemoveField(
            model_name='extractionresult',
            name='url_confidence',
        ),
        migrations.RemoveField(
            model_name='extractionresult',
            name='version_confidence',
        ),
        migrations.RemoveField(
            model_name='extractiontask',
            name='retry_count',
        ),
        migrations.AddField(
            model_name='extractionresult',
            name='confidence_scores',
            field=models.JSONField(default=dict, help_text='Score de confiance pour chaque champ extrait', verbose_name='Scores de confiance'),
        ),
        migrations.AddField(
            model_name='extractionresult',
            name='error_message',
            field=models.TextField(blank=True, help_text="Message d'erreur si l'extraction a échoué", null=True, verbose_name="Message d'erreur"),
        ),
        migrations.AddField(
            model_name='extractionresult',
            name='extracted_data',
            field=models.JSONField(default=dict, help_text="Métadonnées extraites par l'IA au format JSON", verbose_name='Données extraites'),
        ),
        migrations.AddField(
            model_name='extractionresult',
            name='extraction_method',
            field=models.CharField(default='mistral_ai', help_text="Méthode utilisée pour l'extraction (mistral_ai, openai, etc.)", max_length=50, verbose_name="Méthode d'extraction"),
        ),
        migrations.AddField(
            model_name='extractionresult',
            name='model_version',
            field=models.CharField(default='mistral-large-latest', help_text='Version du modèle IA utilisé', max_length=100, verbose_name='Version du modèle'),
        ),
        migrations.AddField(
            model_name='extractionresult',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échec'), ('validated', 'Validé')], default='pending', max_length=20, verbose_name='Statut'),
        ),
        migrations.AddField(
            model_name='extractionresult',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Mis à jour le'),
        ),
        migrations.AddField(
            model_name='extractionresult',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Validé le'),
        ),
        migrations.AddField(
            model_name='extractionresult',
            name='validated_by',
            field=models.ForeignKey(blank=True, help_text='Utilisateur qui a validé les métadonnées', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Validé par'),
        ),
        migrations.AddField(
            model_name='extractiontask',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='extractionresult',
            name='confidence_score',
            field=models.FloatField(default=0.0, help_text="Score de confiance moyen de l'extraction (0.0 à 1.0)", verbose_name='Score de confiance global'),
        ),
        migrations.AlterField(
            model_name='extractionresult',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='extractionresult',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extraction_results', to='documents.document', verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='extractionresult',
            name='processing_time',
            field=models.FloatField(blank=True, help_text='Temps de traitement en secondes', null=True, verbose_name='Temps de traitement'),
        ),
        migrations.AlterField(
            model_name='extractiontask',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Terminé le'),
        ),
        migrations.AlterField(
            model_name='extractiontask',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extraction_tasks', to='documents.document', verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='extractiontask',
            name='error_message',
            field=models.TextField(blank=True, null=True, verbose_name="Message d'erreur"),
        ),
        migrations.AlterField(
            model_name='extractiontask',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Démarré le'),
        ),
        migrations.AlterField(
            model_name='extractiontask',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('started', 'Démarré'), ('success', 'Succès'), ('failure', 'Échec'), ('retry', 'Nouvelle tentative')], default='pending', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='extractiontask',
            name='task_id',
            field=models.CharField(help_text='ID de la tâche Celery', max_length=255, unique=True, verbose_name='ID de tâche'),
        ),
        migrations.AddIndex(
            model_name='extractionresult',
            index=models.Index(fields=['document', '-created_at'], name='extraction__documen_c4f0eb_idx'),
        ),
        migrations.AddIndex(
            model_name='extractionresult',
            index=models.Index(fields=['status'], name='extraction__status_149358_idx'),
        ),
        migrations.AddIndex(
            model_name='extractionresult',
            index=models.Index(fields=['confidence_score'], name='extraction__confide_47e25d_idx'),
        ),
    ]
