# Generated by Django 4.2.7 on 2025-07-23 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rawdocs', '0008_auto_20250718_0547'),
        ('rawdocs', '0010_userprofile'),
    ]

    operations = [
    ]
