# Generated by Django 4.2.7 on 2025-07-23 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawdocs', '0011_merge_0008_auto_20250718_0547_0010_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ailearningmetrics',
            name='entity_performance',
            field=models.JSONField(default=dict, help_text='Performance per entity type'),
        ),
        migrations.AlterField(
            model_name='ailearningmetrics',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='confidence_score',
            field=models.FloatField(default=0.0, help_text='Score IA (0.0–1.0)'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='annotationfeedback',
            name='ai_annotations_before',
            field=models.JSONField(help_text='AI annotations before human correction'),
        ),
        migrations.AlterField(
            model_name='annotationfeedback',
            name='corrections_made',
            field=models.JSONField(help_text='What was corrected: additions, deletions, modifications'),
        ),
        migrations.AlterField(
            model_name='annotationfeedback',
            name='feedback_score',
            field=models.FloatField(default=0.0, help_text='Overall feedback score (0-1)'),
        ),
        migrations.AlterField(
            model_name='annotationfeedback',
            name='human_annotations_after',
            field=models.JSONField(help_text='Final annotations after human validation'),
        ),
        migrations.AlterField(
            model_name='annotationfeedback',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='annotationsession',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='annotationtype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='documentpage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='documentpage',
            name='is_validated_by_human',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='metadatalog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='promptoptimization',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='rawdocument',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
