# Generated by Django 5.2.3 on 2025-10-25 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='extraction_precision',
            field=models.FloatField(blank=True, null=True, verbose_name="Précision d'extraction (%)"),
        ),
        migrations.AddField(
            model_name='document',
            name='image_extraction_quality',
            field=models.FloatField(blank=True, null=True, verbose_name='Qualité extraction images (%)'),
        ),
        migrations.AddField(
            model_name='document',
            name='table_extraction_quality',
            field=models.FloatField(blank=True, null=True, verbose_name='Qualité extraction tableaux (%)'),
        ),
        migrations.AddField(
            model_name='document',
            name='text_extraction_quality',
            field=models.FloatField(blank=True, null=True, verbose_name='Qualité extraction texte (%)'),
        ),
        migrations.AddField(
            model_name='document',
            name='total_elements_detected',
            field=models.IntegerField(blank=True, null=True, verbose_name='Éléments détectés'),
        ),
        migrations.AddField(
            model_name='document',
            name='total_elements_extracted',
            field=models.IntegerField(blank=True, null=True, verbose_name='Éléments extraits avec succès'),
        ),
        migrations.CreateModel(
            name='DocumentExtractionError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_type', models.CharField(choices=[('text_ocr', 'Erreur OCR texte'), ('image_extraction', 'Erreur extraction image'), ('table_parsing', 'Erreur analyse tableau'), ('font_detection', 'Erreur détection police'), ('layout_analysis', 'Erreur analyse mise en page'), ('encoding', 'Erreur encodage'), ('format_corruption', 'Fichier corrompu'), ('memory_limit', 'Limite mémoire'), ('timeout', 'Délai dépassé'), ('unknown', 'Erreur inconnue')], max_length=20, verbose_name="Type d'erreur")),
                ('severity', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyen'), ('high', 'Élevé'), ('critical', 'Critique')], max_length=10, verbose_name='Gravité')),
                ('message', models.TextField(verbose_name="Message d'erreur")),
                ('details', models.JSONField(blank=True, null=True, verbose_name='Détails techniques')),
                ('page_number', models.IntegerField(blank=True, null=True, verbose_name='Numéro de page')),
                ('element_type', models.CharField(blank=True, max_length=50, null=True, verbose_name="Type d'élément")),
                ('suggested_fix', models.TextField(blank=True, null=True, verbose_name='Solution suggérée')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extraction_errors', to='documents.document')),
            ],
            options={
                'verbose_name': "Erreur d'extraction",
                'verbose_name_plural': "Erreurs d'extraction",
                'ordering': ['-created_at'],
            },
        ),
    ]
