# Generated by Django 5.2.3 on 2025-07-02 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='publication_date',
        ),
        migrations.AddField(
            model_name='document',
            name='ema_last_search_date',
            field=models.DateTimeField(blank=True, help_text='Date et heure de la dernière recherche automatique EMA', null=True, verbose_name='Dernière recherche EMA'),
        ),
        migrations.AddField(
            model_name='document',
            name='ema_publication_date',
            field=models.DateField(blank=True, help_text="Date 'Last updated' récupérée du site EMA (dernière mise à jour)", null=True, verbose_name='Dernière mise à jour EMA'),
        ),
        migrations.AddField(
            model_name='document',
            name='ema_reference',
            field=models.CharField(blank=True, help_text='Numéro de référence EMA du document', max_length=100, verbose_name='Référence EMA'),
        ),
        migrations.AddField(
            model_name='document',
            name='ema_search_performed',
            field=models.BooleanField(default=False, help_text='Indique si la recherche automatique sur le site EMA a été effectuée', verbose_name='Recherche EMA effectuée'),
        ),
        migrations.AddField(
            model_name='document',
            name='ema_search_results_count',
            field=models.IntegerField(default=0, help_text='Nombre de résultats trouvés lors de la recherche EMA', verbose_name='Nombre de résultats EMA'),
        ),
        migrations.AddField(
            model_name='document',
            name='ema_similarity_score',
            field=models.FloatField(default=0.0, help_text='Score de similarité entre le titre du document et le résultat EMA (0.0 à 1.0)', verbose_name='Score de similarité EMA'),
        ),
        migrations.AddField(
            model_name='document',
            name='ema_source_url',
            field=models.URLField(blank=True, help_text="URL du document sur le site de l'EMA", verbose_name='URL source EMA'),
        ),
        migrations.AddField(
            model_name='document',
            name='ema_title',
            field=models.CharField(blank=True, help_text="Titre du document tel qu'il apparaît sur le site EMA", max_length=500, verbose_name='Titre EMA'),
        ),
        migrations.AddField(
            model_name='document',
            name='original_publication_date',
            field=models.DateField(blank=True, help_text="Date 'First published' récupérée du site EMA (première publication officielle)", null=True, verbose_name='Première publication EMA'),
        ),
    ]
