# Generated by Django 5.2.3 on 2025-07-03 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_remove_document_publication_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='version',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
