# Generated by Django 5.2.3 on 2025-10-25 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_extraction_precision_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='extraction_precision',
        ),
        migrations.RemoveField(
            model_name='document',
            name='image_extraction_quality',
        ),
        migrations.RemoveField(
            model_name='document',
            name='table_extraction_quality',
        ),
        migrations.RemoveField(
            model_name='document',
            name='text_extraction_quality',
        ),
        migrations.RemoveField(
            model_name='document',
            name='total_elements_detected',
        ),
        migrations.RemoveField(
            model_name='document',
            name='total_elements_extracted',
        ),
        migrations.DeleteModel(
            name='DocumentExtractionError',
        ),
    ]
