# Generated by Django 5.2.3 on 2025-07-03 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_document_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='publication_date',
            field=models.DateField(blank=True, help_text='Date de publication extraite du contenu du document', null=True, verbose_name='Date de publication'),
        ),
    ]
