# Generated by Django 5.2.3 on 2025-07-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_document_publication_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='direct_pdf_url',
            field=models.URLField(blank=True, help_text='URL directe vers le fichier PDF (pour extraction du contenu)', verbose_name='URL directe du PDF'),
        ),
        migrations.AddField(
            model_name='document',
            name='ema_page_url',
            field=models.URLField(blank=True, help_text='URL de la page web EMA contenant les métadonnées du document', verbose_name='URL de la page EMA'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/'),
        ),
    ]
