# Generated by Django 5.2.3 on 2025-07-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_document_direct_pdf_url_document_ema_page_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='direct_pdf_url',
            field=models.URLField(blank=True, help_text='URL directe vers le fichier PDF (pour extraction du contenu)', max_length=255, verbose_name='URL directe du PDF'),
        ),
    ]
